"""fixed Planet model

Revision ID: 0feb668fd495
Revises: cb8050f41f95
Create Date: 2024-10-25 12:07:03.022027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0feb668fd495'
down_revision = 'cb8050f41f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('surface_area', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('moons', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('distance_from_sun', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('namesake', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('namesake')
        batch_op.drop_column('distance_from_sun')
        batch_op.drop_column('moons')
        batch_op.drop_column('surface_area')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
